---

ssh_key: 
  # florentino@ibm.com
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzja77jF9uWRLjlmVr3ONr4Kha6IKl4RHt1zm0mSEwCq3pGyf+COPPDuGyJ2PN8a9TngOSKmJ09jhzl4N2ofWh64ZZAMYsCE1tjilz7VP4UWUR6qLJ6jAS71JskVVyyzzagC+/FEcSiC4T03W3anMWnqmFYBR0DCp7RiJZzaCRhO7CNIcYT2vgzEesEm+QrnUSsYjppAjexrRZdW3JHZ4lq7wCePJLlaoq0cmr1Cl419HAQjIqVt4Gcj2yyKgA4xaMkMclQKBuYj7+pGjl07Dp/+H/ODiZ1Z6oippS4aa/LoV6MKp5LY+Ip4dr5eMtAhojwFXc1x5ftp/RbGezuHeH florentino@ibm.com"

packages:
  to_install:
    - epel-release
    - yum-utils
    - net-tools
    - bind-utils
    - iptables-services
    - htop
    - tree
    - vim
    - policycoreutils-python
    - open-vm-tools
    - ntp
  to_remove:
    -

services:
  to_enable:
    - network
    - vmtoolsd
    - ntpd

  to_disable:
    - NetworkManager
    - firewalld

ntp_servers:
  - "server 0.br.pool.ntp.org"
  - "server 1.br.pool.ntp.org"
  - "server 2.br.pool.ntp.org"
  - "server 3.br.pool.ntp.org"