---
- name: "Update System"
  package:
    name: "*"
    state: latest

- name: "Install Essentials Packages"
  package:
    name: "{{ item }}"
    state: installed
  loop: "{{ packages.to_install }}"

- name: "Systemd Enabled"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ services.to_enable }}"

- name: "Systemd Disabled"
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ services.to_disable }}"

- name: "Selinux Disable"
  selinux:
    state: disabled

- name: "Configure NTP service"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644
  notify: "Restart NTP service"

- name: "Update Host Hostname"
  hostname:
    name: "{{ inventory_hostname }}"