---
- name: "Create group of service"
  group:
    name: sre
    state: present

- name: "Create user of service"
  user:
    name: ansible
    state: present
    generate_ssh_key: yes
    shell: /bin/bash
    append: yes
    groups: ["sre"]

- name: "Make group of service parts sudoers"
  copy:
    src: sudoers
    dest: /etc/sudoers
    backup: yes
    owner: root
    mode: 0644
    validate: /usr/sbin/visudo -cf %s

- name: "Include ssh-key to managed servers"
  template:
    src: authorized_keys.j2
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: 0644