---

- name: Download Containerd
  get_url: 
    url: https://github.com/containerd/containerd/releases/download/v1.2.6/containerd-1.2.6.linux-amd64.tar.gz
    dest: /tmp/containerd-1.2.6.linux-amd64.tar.gz
    mode: 0644
  when: container_engine == "containerd"

- name: Download Runc
  get_url: 
    url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc8/runc.amd64
    dest: /usr/local/sbin/runc
    mode: 0755
  when: container_engine == "containerd"

- name: Extract Containerd
  unarchive: 
    src: /tmp/containerd-1.2.6.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  when: container_engine == "containerd"

- name: Get Systemctl Containerd
  get_url: 
    url: https://raw.githubusercontent.com/containerd/cri/master/contrib/systemd-units/containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: 0644
  when: container_engine == "containerd"

- name: Kubelet system folder
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    owner: root
    group: root
    mode: 0644
  when: container_engine == "containerd"

- name: Containerd Config
  copy:
    src: 0-containerd.conf
    dest: /etc/systemd/system/kubelet.service.d/0-containerd.conf
    owner: root
    group: root
    mode: 0644
  when: container_engine == "containerd"

- name: Crictl Config
  copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: 0644
  when: container_engine == "containerd"

- name: Enable/Start Systemctl Containerd
  systemd:
    name: containerd
    daemon-reload: yes
    enabled: yes
    state: started
  when: container_engine == "containerd"