---
- name: "Remove old configuration of network"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/sysconfig/network-scripts/ifcfg-ens33"
    - "/etc/sysconfig/network-scripts/ifcfg-ens192"

- name: "Configure the network"
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644

- include_tasks: repos.yml

- name: "Update System"
  package:
    name: "*"
    state: latest

- name: "Install Essentials Packages"
  package:
    name: "{{ item }}"
    state: installed
  loop: "{{ packages.to_install }}"

- name: "Systemd Enabled"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services.to_enable }}"

- name: "Systemd Disabled"
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ services.to_disable }}"

- name: "Selinux Disable"
  selinux:
    state: disabled

- name: "Configure NTP service"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644
  notify: "Restart NTP service"

- include_tasks: modules.yml
- include_tasks: sysctl.yml
- include_tasks: containerd.yml
- include_tasks: docker.yml
- include_tasks: swapoff.yml

- name: "Update Host Hostname"
  hostname:
    name: "{{ inventory_hostname }}"
