---

- name: Setup sysctl
  copy:
    src: k8s_sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Sysctl enable
  shell: >
    sysctl --system
  args:
    executable: /bin/bash
  register: sysctl_system