all:
  vars:
    ip_repo: 192.168.7.158
    dns_repo: repo.codar.lab.local
  hosts:
    repo-1.codar.lab.local:
      ansible_host: 192.168.7.158
    repo-2.codar.lab.local:
      ansible_host: 192.168.7.157
  children:
    server:
      hosts:
        repo-1.codar.lab.local:
    client:
      hosts:
        repo-2.codar.lab.local:
