---

- name: "Initialize Kubernetes master with kubeadm init and containerd."
  shell: >
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} 
    --apiserver-advertise-address={{ k8s_master_node_ip }} 
    --cri-socket /run/containerd/containerd.sock --ignore-preflight-errors=all
  register: kubeadmin_init
  args:
    executable: /bin/bash
  when: container_engine == "containerd"
