---
- name: Reset Cluster
  shell: >
    kubeadm reset --force --ignore-preflight-errors=all
  register: kubeadmin_init
  args:
    executable: /bin/bash

- name: Initialize Kubernetes master with kubeadm init.
  shell: >
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} 
    --apiserver-advertise-address={{ k8s_master_node_ip }} 
    --cri-socket /run/containerd/containerd.sock --ignore-preflight-errors=all
  register: kubeadmin_init
  args:
    executable: /bin/bash

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Configure weavenet networking.
  shell: >
    kubectl apply -f {{ default_kubernetes_cni_weavenet_manifestUrl }}
  register: weavenet_result
  args:
    executable: /bin/bash
  when: weavenet_network == true

- name: Cluster token
  shell: >
    kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
  register: K8S_TOKEN
  args:
    executable: /bin/bash

- name: CA Hash
  shell: >
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | 
    openssl rsa -pubin -outform der 2>/dev/null | 
    openssl dgst -sha256 -hex | sed 's/^.* //'
  register: K8S_MASTER_CA_HASH
  args:
    executable: /bin/bash

- name: Add K8S Token and Hash to dummy host
  add_host:
    name:   "K8S_TOKEN_HOLDER"
    token:  "{{ K8S_TOKEN.stdout }}"
    hash:   "{{ K8S_MASTER_CA_HASH.stdout }}" 


- include_tasks: metrics_server.yml