---

- name: "Configure GPG KEY for Elasticsearch Repository"
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: "Elasticsearch Repository"
  yum_repository:
    name: "Elasticsearch"
    description: "Elasticsearch repository for 7.x packages"
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    enabled: yes
    gpgcheck: yes

- name: "Install Elasticsearch"
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - elasticsearch

- name: "Start and enabled Elasticsearch Service"
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: "Confifure Cluster for elasticsearch"
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  when: ( cluster_mode == true )
  notify: "Reload elasticsearch configuration"

- name: "Configure JVM Memory to Elasticsearch"
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: root
    mode: 0644
  notify: "Restart elasticsearch configuration"