---

- name: "Configure GPG KEY"
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: "Configure repository"
  yum_repository:
    name: jenkins
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes

- name: "Install Packages"
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - jenkins

- name: "Inicialize systemd services"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - jenkins