---
- name: Kubernetes Master
  hosts:
    - masters
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'
  roles:
    - {role: common, tags: 'common'}
    - {role: master,  tags: 'master'}

- name: Kubernetes Workers
  hosts:
    - workers
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'
  roles:
    - {role: common, tags: 'common'}
    - {role: worker, tags: 'worker'}


- name: Adicionando Label nos Node Workers
  hosts:
    - master
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'
  tasks:
    - name: Label node to Worker
      shell: >
        kubectl label node {{ item }} node-role.kubernetes.io/worker=
      args:
        executable: /bin/bash
      register: label_node
      with_inventory_hostnames: workers