---
- name: Kubernetes Master
  hosts:
    - master
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'
  roles:
    - {role: metric_server, tags: 'metric_server'}

