---

- name: "Build a new virtual machine on-premise infraestructure"
  hosts:
    - all
  gather_facts: False
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'

  roles:
    - {role: common, tags: "common"}